let myName: string = "Saleem";
console.log("My name is Saleem")
console.log(myName == "Saleem")
console.log("My name is not Saleem")
console.log(myName != "Saleem")
console.log("Saleem is equal to saleem after converting it to lowercase")
console.log(myName.toLocaleLowerCase() == "saleem")
console.log("Saleem is not equal to saleem after converting it to lowercase")
console.log(myName.toLocaleLowerCase() != "saleem")
let mySalary: number = 100000
let yourSalary: number = 150000
console.log("My salary is equal to your salary")
console.log(mySalary == yourSalary)
console.log("My salary is not equal to your salary")
console.log(mySalary != yourSalary)
console.log("My salary is greater than your salary")
console.log(mySalary > yourSalary)
console.log("My salary is less than your salary")
console.log(mySalary < yourSalary)
console.log("My salary is greater than or equal to your salary")
console.log(mySalary >= yourSalary)
console.log("My salary is less than or equal to your salary")
console.log(mySalary <= yourSalary)
console.log("My salary is not equal to your salary and my salary is less than your salary")
console.log(mySalary !== yourSalary && mySalary < yourSalary)
console.log("My salary is not equal to your salary and my salary is greater than your salary")
console.log(mySalary !== yourSalary && mySalary > yourSalary)
console.log("My salary is not equal to your salary or my salary is greater than your salary")
console.log(mySalary !== yourSalary || mySalary > yourSalary)
console.log("My salary is equal to your salary or my salary is greater than your salary")
console.log(mySalary == yourSalary || mySalary > yourSalary)
let courses: string[] = ["Javascript", "Typescript", "Python"]
console.log("Typescript is included in our course list")
console.log(courses.includes("Typescript"))
console.log("Typescript is not included in our course list")
console.log(!courses.includes("Typescript"))