let myCArModel:number = 2004;
let yourCarModel: number = 2014;

console.log("Test 1: My car model is older than your car model.")
console.log(myCArModel < yourCarModel)
console.log("Test 2: Your car model is latest than my car model.")
console.log(yourCarModel > myCArModel)
console.log("Test 3: My car model is not equal to your car model.")
console.log(myCArModel !== yourCarModel)
console.log("Test 4: My car model is older than 2010.")
console.log(myCArModel < 2010)
console.log("Test 5: Your car model is latest than 2010.")
console.log(yourCarModel > 2010)
console.log("Test 6: My car model is latest than your car model.")
console.log(myCArModel > yourCarModel)
console.log("Test 7: Your car model is older than my car model.")
console.log(yourCarModel < myCArModel)
console.log("Test 8: My car model is equal to your car model.")
console.log(myCArModel == yourCarModel)
console.log("Test 9: My car model is latest than 2010.")
console.log(myCArModel > 2010)
console.log("Test 10: Your car model is older than 2010.")
console.log(yourCarModel < 2010)